from app import app_db
from models import User, Team, High5
import datetime

'''
Method used to create 12 inital users to add to the database to put on teams.'''
def create_users():
    user1 = User(user_name='VPeterson', name='Veronica Peterson', email='vpeters2@illinois.edu', password='abc123')
    user2 = User(user_name='RaychHeinz', name='Rachel Heinzinger', email='rheinb2@illinois.edu', password='abc123')
    user3 = User(user_name='Kathy', name='Kathleen Adolf', email='kadol2@illinois.edu', password='abc123')
    user4 = User(user_name='Hunter1994', name='Sam Hunt', email='samh2@illinois.edu', password='abc123')
    user5 = User(user_name='Snewell', name='Sarah Newell', email='sanew2@illinois.edu', password='abc123')
    user6 = User(user_name='Aubs75', name='Aubrey Simons', email='aubsi2@illinois.edu', password='abc123')
    user7 = User(user_name='Josie1', name='Josie Wynveen', email='jwynv2@illinois.edu', password='abc123')
    user8 = User(user_name='LaurenL', name='Lauren Lewis', email='lewis2@illinois.edu', password='abc123')
    user9 = User(user_name='John', name='John Doe', email='johndoe@illinois.edu', password='abc123')
    user10 = User(user_name='Jane', name='Jane Doe', email='janedoe@illinois.edu', password='abc123')
    user11 = User(user_name='Tom', name='Tom Duck', email='tomduck@illinois.edu', password='abc123')
    user12 = User(user_name='Pat', name='Pat Python', email='patpython@illinois.edu', password='abc123')
    app_db.session.add_all([user1, user2, user3, user4, user5, user6, user7, user8, user9, user10, user11, user12])
    app_db.session.commit()

'''
Method used to create the made up team for UIUC Girls Running Club and add to the database.
This team has 8 user members and 11 high5's between them. This will allow the db to have some initial data.'''
def create_running_team():
    user1 = User.query.filter(User.user_name == 'VPeterson').one()
    user2 = User.query.filter(User.user_name == 'RaychHeinz').one()
    user3 = User.query.filter(User.user_name == 'Kathy').one()
    user4 = User.query.filter(User.user_name == 'Hunter1994').one()
    user5 =User.query.filter(User.user_name == 'Snewell').one()
    user6 = User.query.filter(User.user_name == 'Aubs75').one()
    user7 = User.query.filter(User.user_name == 'Josie1').one()
    user8 = User.query.filter(User.user_name == 'LaurenL').one()
    team = Team(name='UIUC Girls Running Club', admin='VPeterson')
    high5_1 = High5(receiver='VPeterson', giver='Kathy', message='Veronica organized an awesome Halloween themed pasta party for all the racers this weekend!', time_posted=datetime.datetime.utcnow(), level=5, team=team)
    high5_2 = High5(receiver='VPeterson', giver='RaychHeinz', message='Veronica brought me my racing flats from my apartment when I realized I forgot them right before race time.', time_posted=datetime.datetime.utcnow(), level=1, team=team)
    high5_3 = High5(receiver='Aubs75', giver='Kathy', message='Aubrey organized an awesome Halloween themed pasta party for all the racers this weekend!', time_posted=datetime.datetime.utcnow(), level=5, team=team)
    high5_4 = High5(receiver='LaurenL', giver='Aubs75', message='Lauren drove all the freshmen members home from their service event even though she did not have to go.', time_posted=datetime.datetime.utcnow(), level=3, team=team)
    high5_5 = High5(receiver='Snewell', giver='Kathy', message='Sarah brought extra Gatorade to practice this week for everyone', time_posted=datetime.datetime.utcnow(), level=2, team=team)
    high5_6 = High5(receiver='Kathy', giver='Aubs75', message='Kathleen stayed after practice to help me organize the uniforms to pass out next week.', time_posted=datetime.datetime.utcnow(), level=1, team=team)
    high5_7 = High5(receiver='VPeterson', giver='Aubs75', message='Veronica helped clean up the fitness center after we got it all muddy from the rainy day.', time_posted=datetime.datetime.utcnow(), level=1, team=team)
    high5_8 = High5(receiver='Hunter1994', giver='RaychHeinz', message='Sam organized an awesome Halloween themed pasta party for all the racers this weekend!', time_posted=datetime.datetime.utcnow(), level=5, team=team)
    high5_9 = High5(receiver='Josie1', giver='Hunter1994', message='Josie talked to the university about donating space in the Union for us to host our philanthropy event.', time_posted=datetime.datetime.utcnow(), level=2, team=team)
    high5_10 = High5(receiver='Josie1', giver='Kathy', message='Josie went door to door around Champaign asking for donations for the philanthropy event.', time_posted=datetime.datetime.utcnow(), level=4, team=team)
    high5_11 = High5(receiver='Aubs75', giver='VPeterson', message='Aubrey made posters to cheer on all the runners for the hometown classic!', time_posted=datetime.datetime.utcnow(), level=2, team=team)
    team.members.append(user1)
    team.members.append(user2)
    team.members.append(user3)
    team.members.append(user4)
    team.members.append(user5)
    team.members.append(user6)
    team.members.append(user7)
    team.members.append(user8)
    app_db.session.add(team)
    app_db.session.add(high5_1)
    app_db.session.add(high5_2)
    app_db.session.add(high5_3)
    app_db.session.add(high5_4)
    app_db.session.add(high5_5)
    app_db.session.add(high5_6)
    app_db.session.add(high5_7)
    app_db.session.add(high5_8)
    app_db.session.add(high5_9)
    app_db.session.add(high5_10)
    app_db.session.add(high5_11)
    app_db.session.commit()

'''
Method used to create the made up team for CS465 Group Project and add it to the db.
This team has 5 user members and 9 high5's between them. Used to have an inital team'''
def create_project_team():
    user1 = User.query.filter(User.user_name == 'VPeterson').one()
    user2 = User.query.filter(User.user_name == 'John').one()
    user3 = User.query.filter(User.user_name == 'Jane').one()
    user4 = User.query.filter(User.user_name == 'Tom').one()
    user5 = User.query.filter(User.user_name == 'Pat').one()
    team = Team(name='CS465 Group 17', admin='VPeterson')
    high5_1 = High5(receiver='VPeterson', giver='John', message='Veronica reminded everyone to turn in their peer evaluations.', time_posted=datetime.datetime.utcnow(), level=1, team=team)
    high5_2 = High5(receiver='VPeterson', giver='Jane', message='Veronica drove me home from the group meeting when it was raining.', time_posted=datetime.datetime.utcnow(), level=1, team=team)
    high5_4 = High5(receiver='Jane', giver='VPterson', message='Jane let me borrow her laptop to code when mine broke.', time_posted=datetime.datetime.utcnow(), level=2, team=team)
    high5_5 = High5(receiver='Jane', giver='Tom', message='Jane brought candy to our meeting on Halloween!', time_posted=datetime.datetime.utcnow(), level=1, team=team)
    high5_6 = High5(receiver='Jane', giver='VPeterson', message='Jane met with extra users for the research checkpoint.', time_posted=datetime.datetime.utcnow(), level=5, team=team)
    high5_7 = High5(receiver='Tom', giver='John', message='Tom went in to extra office hours to get feedback on our project change idea', time_posted=datetime.datetime.utcnow(), level=5, team=team)
    high5_8 = High5(receiver='Pat', giver='Tom', message='Pat went to the store to get supplies to make paper prototypes.', time_posted=datetime.datetime.utcnow(), level=4, team=team)
    high5_9 = High5(receiver='Pat', giver='Jane', message='Pat let us use his apartment to meet for user interviews.', time_posted=datetime.datetime.utcnow(), level=4, team=team)
    team.members.append(user1)
    team.members.append(user2)
    team.members.append(user3)
    team.members.append(user4)
    team.members.append(user5)
    app_db.session.add(team)
    app_db.session.add(high5_1)
    app_db.session.add(high5_2)
    app_db.session.add(high5_4)
    app_db.session.add(high5_5)
    app_db.session.add(high5_6)
    app_db.session.add(high5_7)
    app_db.session.add(high5_8)
    app_db.session.add(high5_9)
    app_db.session.commit()